Vagrant.configure("2") do |config|
  config.vm.box     = "lucid64"
  config.vm.box_url = "http://files.vagrantup.com/lucid64.box"

  config.vm.network :forwarded_port, guest: 3000, host: 3000
  # config.vm.network "33.33.33.10"
  config.vm.network :forwarded_port, guest: 27017, host: 27018

  config.vm.synced_folder "app", "/home/vagrant/app"

  # allow for symlinks in the app folder
  config.vm.provider :virtualbox do |vb|
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/app", "1"]
    vb.customize ["modifyvm", :id, "--memory", "512"]
  end

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "vagrant-node-mongo/cookbooks"
    chef.add_recipe "apt"
    chef.add_recipe "mongodb"
    chef.add_recipe "build-essential"
    chef.add_recipe "nodejs::install_from_package"
    chef.json = {
      "nodejs" => {
        "version" => "0.8.0"
        # uncomment the following line to force
	# recent versions (> 0.8.4) to be built from
	# the source code
	# , "from_source" => true
      }
    }
  end
end
