#!/bin/sh
#
# Copyright 2013 Dean Okamura
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#

# Install Chef
echo "deb http://apt.opscode.com/ `lsb_release -cs`-0.10 main" | sudo tee /etc/apt/sources.list.d/opscode.list
sudo mkdir -p /etc/apt/trusted.gpg.d
gpg --keyserver keys.gnupg.net --recv-keys 83EF826A
gpg --export packages@opscode.com | sudo tee /etc/apt/trusted.gpg.d/opscode-keyring.gpg > /dev/null
sudo apt-get update
sudo apt-get install opscode-keyring
sudo apt-get upgrade
sudo apt-get install chef chef-server
#
# You will be prompted by debconf for the Chef Server URL.
# Put in a value like "http://chef.example.com:4000".
# You will also be prompted for the rabbitmq consumer password and the webui admin password.
# The rabbitmq consumer password MUST NOT be left blank.
#
