#!/bin/ksh
#
# Licensed Materials - Property of IBM
#
# 2013-IBM
#
# (C) Copyright IBM Corp. 2013  All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with
# IBM Corp.
#

if [ -d /opt/IBM/ITM/logs ] ; then
    ITM_LOG_DIR=/opt/IBM/ITM/logs
elif [ -d /opt/ibm/ccm/sma/logs ] ; then
    ITM_LOG_DIR=/opt/ibm/ccm/sma/logs
elif [ -d /opt/ibm/ccm/oslc_pm/logs ] ; then
    ITM_LOG_DIR=/opt/ibm/ccm/oslc_pm/logs
else
    echo "ITM_LOG_DIR not found"
    exit 1
fi
for f in $ITM_LOG_DIR/*
do
    if [ "$(sudo fuser $f)" = "" ] ; then
        rm $f
    fi
done
