#!/bin/ksh
#
# Licensed Materials - Property of IBM
#
# 2013-IBM
#
# (C) Copyright IBM Corp. 2013  All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with
# IBM Corp.
#

if [ -d /opt/IBM/ITM ] ; then
    CANDLEHOME=/opt/IBM/ITM
elif [ -d CANDLEHOME=/opt/ibm/ccm/sma ] ; then
    CANDLEHOME=/opt/ibm/ccm/sma
elif [ -d CANDLEHOME=/opt/ibm/ccm/oslc_pm ] ; then
    CANDLEHOME=/opt/ibm/ccm/oslc_pm
else
    echo "CANDLEHOME not found"
    exit 1
fi
for f in $CANDLEHOME/logs/*
do
    if [ "$(sudo fuser $f)" = "" ] ; then
        rm $f
    fi
done
